version: "3.8"

services:
  web:
    build: .
    environment:
      DB_HOST: "db"
      NODE_ENV: "production"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 384M  # Asignar más a web, menos a db
        reservations:
          memory: 256M
    restart: always

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: vinyls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - default
    # Optimizar la configuración de PostgreSQL para usar menos memoria
    command: postgres -c shared_buffers=32MB -c max_connections=20 -c work_mem=4MB
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  default:
    driver: bridge
